Repository GreenManSK/PA165-D-D-Troops, pull requests merged in 2018-11, with the labels that each got.

#36 Troop DTO + Facade interface
  dnd-troops-api/src/main/java/cz/muni/fi/pa165/w2018/dndtroops/api/dto/TroopChangeDTO.java
  dnd-troops-api/src/main/java/cz/muni/fi/pa165/w2018/dndtroops/api/dto/TroopDTO.java
  dnd-troops-api/src/main/java/cz/muni/fi/pa165/w2018/dndtroops/api/facade/TroopFacade.java
Labels: made changes, review requested

#41 Service and Facade Implementation: Troop
  dnd-troops-backend/src/main/java/cz/muni/fi/pa165/w2018/dndtroops/backend/dao/TroopDao.java
  dnd-troops-backend/src/main/java/cz/muni/fi/pa165/w2018/dndtroops/backend/dao/TroopDaoImpl.java
  dnd-troops-backend/src/test/java/cz/muni/fi/pa165/w2018/dndtroops/backend/dao/TroopDaoTest.java
  dnd-troops-service/src/main/java/cz/muni/fi/pa165/w2018/dndtroops/service/TroopService.java
  dnd-troops-service/src/main/java/cz/muni/fi/pa165/w2018/dndtroops/service/TroopServiceImpl.java
  dnd-troops-service/src/main/java/cz/muni/fi/pa165/w2018/dndtroops/service/configuration/ServiceConfiguration.java
  dnd-troops-service/src/main/java/cz/muni/fi/pa165/w2018/dndtroops/service/facade/TroopFacadeImpl.java
Labels: made changes, review requested

#46 Tests for Troop Facade/Service + minor fixes
  dnd-troops-service/src/main/java/cz/muni/fi/pa165/w2018/dndtroops/service/TroopServiceImpl.java
  dnd-troops-service/src/test/java/cz/muni/fi/pa165/w2018/dndtroops/service/TroopServiceImplTest.java
  dnd-troops-service/src/test/java/cz/muni/fi/pa165/w2018/dndtroops/service/facade/TroopFacadeImplTest.java
Labels: review requested

#48 Tests for GroupService and GroupFacade
  dnd-troops-service/src/test/java/cz/muni/fi/pa165/w2018/dndtroops/service/GroupServiceImplTest.java
  dnd-troops-service/src/test/java/cz/muni/fi/pa165/w2018/dndtroops/service/facade/GroupFacadeImplTest.java
Labels: made changes
